on:
  pull_request:
    branches:
      - main

name: VSCode Marketplace Publish

jobs:
  build:
    name: VSCode Marketplace Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # https://github.com/juliangruber/browser-run/issues/147#issuecomment-580958935
      - run: sudo apt-get install xvfb

      - name: yarn install, compile, and test coverage
        run: |
          yarn install
          yarn compile
          xvfb-run --auto-servernum yarn test

      - name: Publish to VSCode Marketplace
        uses: lannonbr/vsce-action@master
        with:
          args: 'publish -p $VSCE_TOKEN'
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
